# Generated by Django 4.2.6 on 2023-10-26 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('meta_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('profile_pic_url', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auths.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone', 'email'], name='auths_user_phone_a10307_idx'),
        ),
    ]
