# Generated by Django 4.2.6 on 2023-10-28 16:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicMeta',
            fields=[
                ('profile_pic_meta_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('picture_name', models.CharField(blank=True, max_length=50, null=True)),
                ('public_id', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('types', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_id', models.CharField(blank=True, max_length=50, null=True)),
                ('folder', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.CharField(blank=True, max_length=50, null=True)),
                ('signature', models.CharField(blank=True, max_length=50, null=True)),
                ('version_id', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('meta_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('profile_pic_url', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('doj', models.DateTimeField(default=datetime.datetime(2023, 10, 28, 21, 41, 56, 995973))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_meta', to='auths.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone', 'email'], name='auths_user_phone_a10307_idx'),
        ),
        migrations.AddField(
            model_name='profilepicmeta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pic_meta', to='auths.user'),
        ),
    ]
