# Generated by Django 4.2.6 on 2023-10-26 07:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_usermeta_doj'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='doj',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 13, 14, 45, 478680)),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_meta', to='auths.user'),
        ),
        migrations.CreateModel(
            name='ProfilePicMeta',
            fields=[
                ('profile_pic_meta_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('types', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_id', models.CharField(blank=True, max_length=50, null=True)),
                ('folder', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.CharField(blank=True, max_length=50, null=True)),
                ('signature', models.CharField(blank=True, max_length=50, null=True)),
                ('version_id', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pic_meta', to='auths.user')),
            ],
        ),
    ]
