# Generated by Django 4.2.6 on 2023-10-26 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_usermeta_bio_alter_usermeta_doj_alter_usermeta_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicmeta',
            name='picture_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='doj',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 13, 18, 37, 178898)),
        ),
    ]
