# Generated by Django 4.2.6 on 2023-10-27 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_profilepicmeta_picture_name_alter_usermeta_doj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='doj',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 21, 37, 5, 907439)),
        ),
    ]
