# Generated by Django 4.2.1 on 2023-11-08 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0009_alter_section_created_at'),
        ('posts', '0008_alter_post_created_at'),
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='sharedpost',
            name='shared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 18, 57, 48, 300655)),
        ),
        migrations.AlterField(
            model_name='sharedsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sections.section'),
        ),
        migrations.AlterField(
            model_name='sharedsection',
            name='shared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 18, 57, 48, 298655)),
        ),
    ]
