# Generated by Django 4.2.1 on 2023-11-08 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_alter_sharedpost_post_alter_sharedpost_shared_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedpost',
            name='shared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 18, 58, 9, 148655)),
        ),
        migrations.AlterField(
            model_name='sharedsection',
            name='shared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 18, 58, 9, 146655)),
        ),
    ]
