# Generated by Django 4.2.1 on 2023-11-08 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0005_remove_sharedpost_id_remove_sharedsection_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedpost',
            old_name='to_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sharedsection',
            old_name='to_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='sharedpost',
            name='shared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 21, 21, 33, 60964)),
        ),
        migrations.AlterField(
            model_name='sharedsection',
            name='shared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 21, 21, 33, 59963)),
        ),
    ]
