# Generated by Django 4.2.6 on 2023-10-28 16:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0002_alter_section_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 10, 28, 21, 43, 46, 950666))),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='sections.section')),
            ],
        ),
        migrations.CreateModel(
            name='PostFileMeta',
            fields=[
                ('post_file_meta_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('file_url', models.CharField(blank=True, max_length=100, null=True)),
                ('public_id', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('types', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_id', models.CharField(blank=True, max_length=50, null=True)),
                ('folder', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.CharField(blank=True, max_length=50, null=True)),
                ('signature', models.CharField(blank=True, max_length=50, null=True)),
                ('version_id', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pic_meta', to='posts.post')),
            ],
            options={
                'indexes': [models.Index(fields=['file_name'], name='posts_postf_file_na_2c21d8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title'], name='posts_post_title_e7697c_idx'),
        ),
    ]
