# Generated by Django 4.2.6 on 2023-10-28 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0002_alter_usermeta_doj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('section_name', models.CharField(blank=True, max_length=100, null=True)),
                ('section_about', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 10, 28, 21, 42, 11, 312986))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='auths.user')),
            ],
            options={
                'indexes': [models.Index(fields=['section_name'], name='sections_se_section_7c4a48_idx')],
            },
        ),
    ]
