# Generated by Django 4.2.6 on 2023-10-27 16:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0005_alter_usermeta_doj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('section_name', models.CharField(blank=True, max_length=100, null=True)),
                ('section_about', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 10, 27, 21, 37, 6, 897436))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='auths.user')),
            ],
        ),
    ]
