# Generated by Django 4.2.1 on 2023-11-05 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_alter_section_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='visibility',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 18, 35, 42, 591917)),
        ),
    ]
