# Generated by Django 4.2.1 on 2023-11-05 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_section_visibility_alter_section_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 18, 36, 27, 765963)),
        ),
    ]
