# Generated by Django 4.2.1 on 2023-11-08 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0011_alter_section_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 19, 0, 51, 349726)),
        ),
    ]
